---
- name: Install latest apps on all macs
  hosts: macs
  vars:
    mac_apps: "{{ lookup('file', '../../app_lists/mac_apps.txt').splitlines() }}"
  tasks:
    - name: Install Xcode command line tools
      command: xcode-select --install
      args:
        creates: /Library/Developer/CommandLineTools/usr/bin/git

    - name: Check if Homebrew is installed
      shell: command -v brew
      args:
        executable: /bin/bash
      register: homebrew_check
      failed_when: homebrew_check.rc not in [0, 1]
      changed_when: false

    - name: Install Homebrew
      command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /usr/local/bin/brew
      when: homebrew_check.rc != 0

    - name: Install Mac apps
      homebrew:
        name: "{{ item }}"
        state: latest
      loop: "{{ mac_apps }}"
